stages:
  - build
  - distribute

build:
  stage: build
  image: node:lts-alpine3.19
  tags:
    - docker
    - amd64

  before_script:
    - apk update
    - apk add curl
    - apk add xz
    - apk add --no-cache git
    - npm install -g pnpm

  script:
    # Install all dependencies
    - pnpm install
    # Build the distribtion
    - pnpm build
    # Compress the distribution in the artefact file
    - tar cf seacat-auth-webui.tar dist
    - lzma -9 -e -T 0 seacat-auth-webui.tar
    # Calculate the checksum
    - sha256sum seacat-auth-webui.tar.xz > seacat-auth-webui.tar.xz.sha256
  artifacts:
    paths:
      - seacat-auth-webui.tar.lzma
      - seacat-auth-webui.tar.xz.sha256


azure main:
  stage: distribute
  image: mcr.microsoft.com/azure-cli

  tags:
    - docker
    - amd64

  dependencies:
    - build

  only:
    - main

  script:
    - az storage blob upload --overwrite --file seacat-auth-webui.tar.lzma --container-name "\$web" --name "seacat-auth/master/seacat-auth-webui.tar.lzma" --connection-string "$AZURE_STORAGE_CONNECTION_STRING"
    - az storage blob upload --overwrite --file seacat-auth-webui.tar.xz.sha256 --container-name "\$web" --name "seacat-auth/master/seacat-auth-webui.tar.xz.sha256" --connection-string "$AZURE_STORAGE_CONNECTION_STRING"

azure tags:
  stage: distribute
  image: mcr.microsoft.com/azure-cli

  tags:
    - docker
    - amd64

  dependencies:
    - build

  only:
    - tags

  script:
    - az storage blob upload --overwrite --file seacat-auth-webui.tar.lzma --container-name "\$web" --name "seacat-auth/${CI_COMMIT_TAG}/seacat-auth-webui.tar.lzma" --connection-string "$AZURE_STORAGE_CONNECTION_STRING"
    - az storage blob upload --overwrite --file seacat-auth-webui.tar.xz.sha256 --container-name "\$web" --name "seacat-auth/${CI_COMMIT_TAG}/seacat-auth-webui.tar.xz.sha256" --connection-string "$AZURE_STORAGE_CONNECTION_STRING"
